name: Super Linter

on:
  workflow_call:
    inputs:
      language:
        type: string
env: 
  FILTER_REGEX_EXCLUDE: .github/workflows/.*
  
jobs:
  linter:
    runs-on: [ ubuntu-latest ]
    name: Lint Code Base
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
#       with:
#         fetch-depth: 2

    - name: SuperLint Code Base
      uses: github/super-linter/slim@v4
      env:
        VALIDATE_ALL_CODEBASE: false
        DEFAULT_BRANCH: main
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
